### ISSUE TITLE
Linux systems!

### ISSUE THREAD

**Issue by Dulluhan** [starthacking/starthacking.github.io#1]
Hey, this projects looks great, I would love to help people setup linux systems and environments too! I would like to help create that section, let me know what you think.

**Comment by anishathalye** [comment]
Sure, sounds great! You can claim that section (I'm going to be focusing on authoring Windows + Mac content for this weekend).

You can follow the structure used for the rest of the project (see the mac stuff as an example), and let us know if you need any input on anything.
