### ISSUE TITLE
Adding Web Track Information

### ISSUE THREAD

**Issue by moinnadeem** [starthacking/starthacking.github.io#15]
Hey guys!

My plan is to add some information on how the Web Track works. It follows as this:

- What is the internet?
- How does the internet work?
----- My plan is to try and talk about what happens from when you type in a URL to seeing it on the screen. 
----- Introduce internet infrastructure in this section
- What web apps are, and how they work!
---- Introduce HTML + CSS + JS here.
 
- Motivational message that you've learned what you need to, now go off and build something!

Note that I'm only going to teach how things work, not necessarily help them build something. Is this what I should be doing?

**Comment by michaelsilver** [comment]
All of this looks perfect! Exactly what we want in the "TODO" part of https://starthacking.org/web/. Thanks @moinnadeem 😄

**Comment by cmnord** [comment]
Thanks @moinnadeem !
