### ISSUE TITLE
Add disqus

### ISSUE THREAD

**Issue by Bekt** [starthacking/starthacking.github.io#2]
Add a commenting system such as disqus (https://disqus.com/).

That way, people can help others if they are experiencing difficulties.

**Comment by anishathalye** [comment]
Hmm, we could do that.

Most wikis avoid having a comment system though, and a comment system is probably not going to provide people real-time support for people at hackathons.

I don't really have a strong opinion about this either way. Let's leave this open and see what other people think.

**Comment by PacketPerception** [comment]
You could encourage use of chat rooms, like [gitter](https://gitter.im/)

**Comment by anishathalye** [comment]
Yeah. Or just posting in the Hackathon Hackers Facebook group or something. I wonder if there is a HH chat channel somewhere.
