### ISSUE TITLE
Create adminstrator accounts? on windows systems

### ISSUE THREAD

**Issue by slow987** [starthacking/starthacking.github.io#4]

**Comment by anishathalye** [comment]
Hi, I'm not quite sure what you're asking about. Could you please elaborate?

**Comment by slow987** [comment]
How to create an administrator account for windows system?

**Comment by anishathalye** [comment]
Hmm...

StartHacking.org is about [this type of hacker](http://en.wikipedia.org/wiki/Hacker_%28term%29#Programmer_subculture_of_hackers).

I think this question is asking about privilege escalation / admin account creation from a non-admin account on Windows systems, which is a topic we do not wish to include on this site.
